Training sections
iit-ideashop/safety-quiz pull request #15
Opened 2021-07-16 04:54 UTC by harshahemanth

categorising into sections available, locked, in-progress and completed

2021-07-16 17:17 UTC, pkarnia requested changes
I will review / test again once these changes have been made.

2021-07-16 17:17 UTC, pkarnia commented on safety-quiz/userflow.py
> +            available_list.append(i)
When I test this function I get the same items in locked and completed.

2021-07-16 17:56 UTC, harshahemanth commented on safety-quiz/userflow.py
> +        if Training.completed(training):
No, I'm looping though the ovarall_list and checking with completed function, 
"for training in overall_training"

2021-07-19 15:34 UTC, harshahemanth commented on safety-quiz/userflow.py
> +        if Training.completed(training):
Changed

2021-07-19 15:35 UTC, closed without merging

2021-07-19 15:35 UTC, harshahemanth commented
Creating another PR